name = "prosub"
compatibility_date = "2025-07-22"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "KV"
id = "e464ed9308e04d8aa4bdf38b1f3def3c"
preview_id = "e464ed9308e04d8aa4bdf38b1f3def3c"

[[d1_databases]]
binding = "DB"
database_name = "prosub-db"
database_id = "12135af2-6981-42ef-b969-44771903e858"