name = "prosub"
compatibility_date = "2025-07-22"

[[kv_namespaces]]
binding = "KV"
id = "e464ed9308e04d8aa4bdf38b1f3def3c"
preview_id = "e464ed9308e04d8aa4bdf38b1f3def3c"

[[d1_databases]]
binding = "DB"
database_name = "prosub-db"
database_id = "prosub-db-id"