name = "prosub"
compatibility_date = "2025-07-22"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "KV"
id = "3afdd496f196482880762e55b480da4d"
preview_id = "3afdd496f196482880762e55b480da4d"

[[d1_databases]]
binding = "DB"
database_name = "prosub-db"
database_id = "12135af2-6981-42ef-b969-44771903e858"